# Generated by Django 5.1.1 on 2024-09-26 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ShutterChallenge', '0001_initial'),
        ('SnapUsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255, null=True)),
                ('caption', models.TextField(null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('competition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShutterChallenge.lomba')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SnapUsers.pengguna')),
            ],
        ),
        migrations.CreateModel(
            name='DataExif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_model', models.CharField(max_length=255, null=True)),
                ('aperture', models.CharField(max_length=20, null=True)),
                ('exposure_time', models.CharField(max_length=20, null=True)),
                ('iso', models.CharField(max_length=10, null=True)),
                ('focal_length', models.CharField(max_length=20, null=True)),
                ('gps_latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LensGallery.foto')),
            ],
        ),
    ]
