# Generated by Django 5.1.1 on 2024-10-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LensGallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='file_path',
        ),
        migrations.AddField(
            model_name='foto',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/photos/'),
        ),
    ]
