# Generated by Django 5.1.1 on 2024-10-29 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LensGallery', '0002_remove_foto_file_path_foto_file_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataexif',
            name='gps_latitude',
        ),
        migrations.RemoveField(
            model_name='dataexif',
            name='gps_longitude',
        ),
    ]
