# Generated by Django 5.1.1 on 2024-09-26 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LensGallery', '0001_initial'),
        ('SnapUsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LensGallery.foto')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SnapUsers.pengguna')),
            ],
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
                ('comment', models.TextField(null=True)),
                ('scoring_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('judge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SnapUsers.juri')),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LensGallery.foto')),
            ],
        ),
    ]
